language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

env:
    -
    - LANG=

install:
    - python setup.py --quiet install

script:
    - python setup.py test
    - ./cram.py --preserve-env ./tests/simple.t
